# Generated by Django 4.2 on 2023-04-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_delete_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
